require('plugins-config.nvim-tree-config')
require('plugins-config.fzf-config')
require('plugins-config.lsp-configs')
require('plugins-config.vimwiki-config')
require('plugins-config.treesitter-config')
